language: python
sudo: false
python:
  - "3.8"
  - "3.9"
  - "3.10"
env:
  - REQUIREMENTS="django>=3.0,<3.2"
  - REQUIREMENTS="django>=4.0,<4.2"
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install flake8 coveralls $REQUIREMENTS
  - pip install -e .
script:
  - flake8 django_crontab --ignore=E501
  - DJANGO_SETTINGS_MODULE=tests.settings nosetests --with-coverage --cover-package=django_crontab
after_success:
  - coveralls
