name: Django Crontab Tests

env: GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9, "3.10"]
        django-version: ["3.2.15", 4.1]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install -U pip
        pip install flake8 coveralls nose mock django==${{ matrix.django-version }}
        pip install -e .
    - name: Run Style Guide
      run: |
        flake8 django_crontab --ignore=E501,E722,W391
    - name: Run Tests
      run: |
        DJANGO_SETTINGS_MODULE=tests.settings nosetests --with-coverage --cover-package=django_crontab
    - name: Run Post-test Coverage
      run: |
        coveralls
